export const adminKeys = {
    all: ['admin'] as const,
    users: () => [...adminKeys.all, 'users'] as const,
    user: (id: number) => [...adminKeys.users(), id] as const,
    devices: () => [...adminKeys.all, 'devices'] as const,
    device: (id: number) => [...adminKeys.devices(), id] as const,
    companies: () => [...adminKeys.all, 'companies'] as const,
    company: (id: number) => [...adminKeys.companies(), id] as const,
    trips: () => [...adminKeys.all, 'trips'] as const,
    trip: (id: number) => [...adminKeys.trips(), id] as const,
    tripPhoneViewers: (id: number, page: number, size: number) =>
        [...adminKeys.trips(), id, 'phone-viewers', page, size] as const,
    tripViewers: (id: number, page: number, size: number) =>
        [...adminKeys.trips(), id, 'viewers', page, size] as const,
    tripBumps: (id: number, page: number, size: number) =>
        [...adminKeys.trips(), id, 'bumps', page, size] as const,
    blockedAuthors: () => [...adminKeys.trips(), 'blocked-authors'] as const,
    subscriptions: () => [...adminKeys.all, 'subscriptions'] as const,
    vehicles: () => [...adminKeys.all, 'vehicles'] as const,
    vehicle: (id: number) => [...adminKeys.vehicles(), id] as const,
    properties: () => [...adminKeys.all, 'properties'] as const,
    property: (id: number) => [...adminKeys.properties(), id] as const,
    chats: () => [...adminKeys.all, 'chats'] as const,
    chat: (id: number) => [...adminKeys.chats(), id] as const,
    supportChats: () => [...adminKeys.chats(), 'support'] as const,
    analytics: () => [...adminKeys.all, 'analytics'] as const,
    reports: () => [...adminKeys.all, 'reports'] as const,
    currencies: () => [...adminKeys.all, 'currencies'] as const,
    bookingBots: (onlyUnlinked: boolean) => [...adminKeys.all, 'booking-bots', onlyUnlinked] as const,
    bookingBot: (id: number) => [...adminKeys.all, 'booking-bot', id] as const,
    celeryTasks: () => [...adminKeys.all, 'celery-tasks'] as const,
    celeryTask: (id: number) => [...adminKeys.celeryTasks(), id] as const,
    celeryWorkers: () => [...adminKeys.all, 'celery-workers'] as const,
    celeryActive: () => [...adminKeys.all, 'celery-active'] as const,
    celeryRuns: (filters: unknown) =>
        [...adminKeys.all, 'celery-runs', filters] as const,
    celeryRun: (id: number) => [...adminKeys.all, 'celery-run', id] as const,
    celeryRunsSummary: (windowHours: number) =>
        [...adminKeys.all, 'celery-runs-summary', windowHours] as const,
    seeders: () => [...adminKeys.all, 'seeders'] as const,
    notifications: () => [...adminKeys.all, 'notifications'] as const,
    notification: (id: number) => [...adminKeys.notifications(), id] as const,
    ads: () => [...adminKeys.all, 'ads'] as const,
    ad: (id: number) => [...adminKeys.ads(), id] as const,
    adStats: (id: number) => [...adminKeys.ad(id), 'stats'] as const,
    services: () => [...adminKeys.all, 'services'] as const,
    service: (id: number) => [...adminKeys.services(), id] as const,
    serviceGroups: () => [...adminKeys.services(), 'groups'] as const,
    appSettings: () => [...adminKeys.all, 'app-settings'] as const,
    regions: (q?: string, limit?: number) =>
        [...adminKeys.all, 'regions', q ?? null, limit ?? null] as const,
    region: (id: number) => [...adminKeys.all, 'region', id] as const,
    complaints: () => [...adminKeys.all, 'complaints'] as const,
    complaint: (id: number) => [...adminKeys.complaints(), id] as const,
    complaintReasons: () => [...adminKeys.all, 'complaint-reasons'] as const,
    reviews: () => [...adminKeys.all, 'reviews'] as const,
    news: () => [...adminKeys.all, 'news'] as const,
    newsItem: (id: number) => [...adminKeys.news(), id] as const,
    referralSettings: () => [...adminKeys.all, 'referral', 'settings'] as const,
    referralReport: (limit: number) =>
        [...adminKeys.all, 'referral', 'report', limit] as const,
    botTypes: () => [...adminKeys.all, 'bot-types'] as const,
    moderation: () => [...adminKeys.all, 'moderation'] as const,
    moderationBots: () => [...adminKeys.moderation(), 'bots'] as const,
    moderationSettings: (botId?: number) =>
        [...adminKeys.moderation(), 'settings', botId ?? null] as const,
    moderationChats: () => [...adminKeys.moderation(), 'chats'] as const,
    moderationLogs: () => [...adminKeys.moderation(), 'logs'] as const,
    fuelStations: () => [...adminKeys.all, 'fuel', 'stations'] as const,
    fuelReports: () => [...adminKeys.all, 'fuel', 'reports'] as const,
}
